---
packages:
  - ca-certificates 
  - curl 
  - gnupg 
  - lsb-release
  - python3-pip
  - python3-setuptools


docker_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin
...